# SavvaRealm — Forge 1.20.1 dedicated server
# После первого запуска часть строк может пересортироваться — это нормально.

motd=SavvaRealm | Forge 1.20.1
level-name=savva-world
max-players=20
difficulty=normal
gamemode=survival
pvp=true
enforce-whitelist=false
white-list=false
online-mode=true
allow-flight=false
spawn-protection=16
view-distance=10
simulation-distance=10
max-tick-time=60000
enable-command-block=false
enable-query=false
enable-rcon=false
server-port=25565
